### ISSUE TITLE
Nest thermostat showing "null - null"

### ISSUE THREAD

**Issue by bachya** [home-assistant/home-assistant-polymer#1051]
Our Nest Thermostat is currently set to heat at a single target temperature; starting today, the UI began showing this:

<img width="338" alt="screen shot 2018-03-30 at 4 28 02 pm" src="https://user-images.githubusercontent.com/47216/38156124-f75a1d62-3438-11e8-9ff2-5d64ae8bf8c8.png">

Although this data is correct (in that min and max targets are, indeed, `null`):

<img width="994" alt="screen shot 2018-03-30 at 5 15 04 pm" src="https://user-images.githubusercontent.com/47216/38156773-f34bfca4-343d-11e8-8fbf-96fc8585c8bf.png">

...shouldn't the platform show the target temperature?

**EDIT:** had an incorrect second screenshot.

**Comment by balloob** [comment]
Which version of Home Assistant are you using?

**Comment by bachya** [comment]
@balloob 0.66.0 (sorry, should have included that).

The only anecdotal info I can give: it seemed to happen this morning when I randomly tried the `climate.turn_off` and `climate.turn_on` service calls. Can't imagine that's a problem, but FYI.

**Comment by balloob** [comment]
So it is caused by #1037. But the bug is in the backend: we should not include a target temp range if operation mode is set to heat.

**Comment by balloob** [comment]
And the backend bug is related to https://github.com/home-assistant/architecture/issues/22

**Comment by balloob** [comment]
@c727 do you think that we should include temporary null checks for attributes?

**Comment by c727** [comment]
Hmz. Someone else has to fix it please, currently not at home

**Comment by balloob** [comment]
Done

**Comment by moskovskiy82** [comment]
I also have this bug. But not only with the nulls but also extra controls are  now shown. Wasn't the case in 0.65

![image](https://user-images.githubusercontent.com/15857592/38161898-ee30de0e-34df-11e8-8326-b7b6ff842436.png)

**Comment by titilambert** [comment]
We have the same issue with ecobee climate

**Comment by moskovskiy82** [comment]
For me the fix in 0.66.1 didn't work Still the same
![image](https://user-images.githubusercontent.com/15857592/38182780-641c96ca-3644-11e8-9310-0325d89cbe5e.png)

**Comment by MartinHjelmare** [comment]
Have you done a hard refresh of the browser page? Ctrl + shift + r in chrome.

**Comment by bachya** [comment]
@MartinHjelmare is right on the money: a hard refresh does the trick!

<img width="337" alt="screen shot 2018-04-02 at 1 05 16 pm" src="https://user-images.githubusercontent.com/47216/38211070-83b6724e-3676-11e8-8d1b-696ef2fd8941.png">

**Comment by moskovskiy82** [comment]
OK nulls are gone. But the problem with several temp controls is still there 
![image](https://user-images.githubusercontent.com/15857592/38226894-6dcfb25e-3704-11e8-822d-7c9321892056.png)

**Comment by MartinHjelmare** [comment]
It might be related to supported features. I think we need to make those conditional now in the mysensors platform. I think this is a separate issue.

**Comment by NovapaX** [comment]
There's two approaches to this. Either change supported features, or disable/hide controls based on the state.
I would prefer the latter (like we do with the light controls) as supported features is a given for a device, and should not change based on its state...

**Comment by MartinHjelmare** [comment]
Mysensors is a bit special as the features depends on the sketch the user writes. We have to support different sketches. It's comparable to different types of devices.

**Comment by moskovskiy82** [comment]
@MartinHjelmare Shall i open a separate issue on HA? I believe you are the main driving force for mysensors platform so you are already aware of the issue,,,

**Comment by MartinHjelmare** [comment]
Yes I'm aware and it's now on my todo. You can open an issue if you want. It doesn't hurt.
