### ISSUE TITLE
View picker broken in Edge (Creators update)

### ISSUE THREAD

**Issue by AnderssonPeter** [home-assistant/home-assistant-polymer#272]
The teal bar where the Hambuger menu and all the views/groups are listen is shrunken in Edge on windows 10 creators update.
This issue seems to exist on both phones and PC's

See screenshot below:
![wp_ss_20170504_0001](https://cloud.githubusercontent.com/assets/1308309/25700482/374aba6e-30c8-11e7-89b1-2bbb6a583700.png)

**Comment by arsaboo** [comment]
Groups are working for me, but the blue bar on the top is messed up.

![image](https://cloud.githubusercontent.com/assets/18319734/25703866/4f68610a-30a5-11e7-9b53-650490fc9dc3.png)

**Comment by AnderssonPeter** [comment]
@arsaboo i guess i confused groups and view, but yea groups are working view aren't.

**Comment by balloob** [comment]
I don't have a Windows machine to test this with.

**Comment by AnderssonPeter** [comment]
If i add width: 100% to the element `<app-header>` it seems to resolve the issue (done with the html debugger).
So adding the following css should fix the issue
```css
app-header
{
    width: 100%;
}
```

**Comment by AnderssonPeter** [comment]
@balloob if you ever need to test on windows, Microsoft provides free virtual machines just for this, they can be found under https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and they provide the images for multiple virtualization engines.

**Comment by ryanwinter** [comment]
There is also an issue with the paper-menu on the side. When you click on an item it disappears and then the menu becomes un-navigatable.

**Comment by ryanwinter** [comment]
Clicking on states push the state menu down the bottom and kinda greyed out:

![image](https://cloud.githubusercontent.com/assets/10238039/25767292/d8d3ce04-31ac-11e7-9416-bc17fa3a37d2.png)

**Comment by Danthekilla** [comment]
I can confirm this is still an issue. It was happening all the way back in January also. https://github.com/home-assistant/home-assistant/issues/5695#event-1071313665


@balloob 
> I don't have a Windows machine to test this with.

I agree with anderson, you should get a VM for testing from microsoft here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

You can download a VM for both the current and future branch of edge for testing. You can also use IE11 in edge rendering mode for testing.

**Comment by ryanwinter** [comment]
Is this a problem with the Polymer library? I noticed it looks like we are using v1.8.

**Comment by ryanwinter** [comment]
This issues is no longer reproducable in 0.48.1 and Microsoft Edge 40.15063.0.0.

**Comment by pkozul** [comment]
Yep, already working now even in the 0.48.0 official release. Great!
