### ISSUE TITLE
Target Selector does not include diagnostic entities in blueprint

### ISSUE THREAD

**Issue by Blackshome** [home-assistant/home-assistant-polymer#27982]
### The problem

When using a target selector in a blueprint with a device_class: battery it show that there are no entities but there are entities. You can see the Shelly smoke detector in the kitchen for the device but there is no battery entity. Then in area kitchen it also shows no battery entity

```
          selector:
            target:
              entity:
                device_class: battery

```

![Image](https://github.com/user-attachments/assets/6f066141-25f2-4f5f-bca4-030dcca069ca)

The blueprint link if you like to see the working version of this [click here](https://community.home-assistant.io/t/low-battery-notifications-actions/653754)

### What version of Home Assistant Core has the issue?

core-2025.11.2

### What was the last working version of Home Assistant Core?

core-2025.10.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Target Selector

### Link to integration documentation on our website

https://www.home-assistant.io/docs/blueprint/selectors#target-selector

### Example YAML snippet

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by karwosts** [comment]
I suspect this is already fixed this month as it seems to be working correctly on dev, not sure which PR though. Please recheck in 2025.12.

**Comment by Blackshome** [comment]
Thanks @karwosts for the info! Will check it in 2025.12 and close this then.

**Comment by Blackshome** [comment]
@karwosts confirmed this has been fixed in 2025.12 dev. Closing issue

**Comment by Blackshome** [comment]
Just tested it again on 2025.12.3 and the problem is still there. Reopened the bug

**Comment by karwosts** [comment]
Can you give some more detail. 

Please show screenshot of what you have selected, and please give the individual entity details for each entity that you expect to be listed but does not show (specifically attributes).

**Comment by Blackshome** [comment]
Sure.... Below is the screen shot of the same entity. You can see the battery is in the device and in the kitchen. The device shows "0" entities and the area kitchen shows "0" entities. This is the blueprint that was used for this test in the **Battery Settings** section [Click here](https://community.home-assistant.io/t/low-battery-notifications-actions/653754). It should show the battery entity in the device and in the area.

![Image](https://github.com/user-attachments/assets/76d6bcd4-ee61-4432-9120-6b914ac67ed2)

**Comment by karwosts** [comment]
Is the battery a diagnostic sensor or hidden? I don't believe either of those can be selected by device or area.

**Comment by Blackshome** [comment]
The automation works and if you exclude the device or the area kitchen then the battery wont be reported, so that's all good. It is just not showing the entity for the device or area. This is the input code for the blueprint.

```
        exclude_sensors:
          name: Excluded Battery Sensors (Optional)
          description: >
            Choose the battery sensors to exclude when the automation runs.


            The automation will attempt to detect all battery sensors in Home Assistant, including those of your phones, tablets, smartwatches, and more.
            However, it may not always be necessary or desirable to monitor all of these batteries.
            Selecting those battery sensors here will exclude them from your notifications.
          default: { entity_id: [] }
          selector:
            target:
              entity:
                device_class: battery
```

![Image](https://github.com/user-attachments/assets/7f5d41e9-e4d8-4802-b89b-2a07e2be0e51)

![Image](https://github.com/user-attachments/assets/be8045ac-f79f-4d76-8746-abc94e5334e7)

![Image](https://github.com/user-attachments/assets/bf7d223d-ea30-4979-969a-e19e80793471)

**Comment by karwosts** [comment]
Hmm yeah I think this is just how the target selector is designed to work, but I can see that it's maybe not as useful in some cases. 

Generally target selector is intended for use with an entity service, and entity services by design don't target diagnostic entities when referenced via an area or device. So in those usecases it is correct for it to show that there is no entity targeted by that service, so it says "0 entities". 

For use in a blueprint using different rules than the entity service that does care about diagnostic entities referenced by area or device, there would almost need to be a different flavor or option to the target picker to modify the default behavior.

**Comment by Blackshome** [comment]
Yeah, but JLo, French etc said it will work everywhere on https://www.youtube.com/watch?v=aFsINNDTPjU at around 26 min to 27 min mark and it is not working.
