### ISSUE TITLE
Hassio is refreshing constantly

### ISSUE THREAD

**Issue by blattmann** [home-assistant/home-assistant-polymer#4894]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

As described already in this [post](https://community.home-assistant.io/t/hassio-refreshing-constantly/157771) by another member - the UI keeps refreshing
I’m running " Home Assistant 0.105.4" on a Raspberry Pi4. I also updated to the latest OS "HassOS 3.10".

This issue prevents me from working with Node-Red as the page is refreshing every more or less 30 seconds. Other views are also permanently refreshed - so it's not related to Node-Red.

## Expected behavior

No auto-refresh.

## Steps to reproduce

Enter Home Assistant. Select anything in the navigation. Open the network-tab of the Chrome dev tools. Clear any previous logs inside the network tab if present. Wait less than a minute - the view will get refreshed and several requests will be visible in the log.

## Environment

- Home Assistant release with the issue: _"Home Assistant 0.105.4" on "HassOS 3.10"_
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): _Lovelace_
- Browser and browser version: _Chrome (latest version) and Firefox (latest version)_
- Operating system: _OSX Catalina_
- Hardware: _Raspberry Pi4_

## Problem-relevant configuration

```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 184
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# MQTT Broker
mqtt:
  broker: !secret mqtt_url
  username: !secret mqtt_username
  password: !secret mqtt_password

# IFTTT
ifttt:
  key: !secret ifttt_api_key

default_config:

# Enable Nabu Casa
cloud:

# Enable Mobile App
mobile_app:

# Enable the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enable tuya app
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 34
  platform: smart_life

# Enable API mode
api:

# Get system health
system_health:

# Enables configuration UI
config:

# Checks for available updates
updater:

recorder:
  purge_keep_days: 2
  purge_interval: 2

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

### Track the sun ###
sun:

### Text to speech ###
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en'

#lovelace:
#  mode: yaml

### get breaking changes ###
breaking_changes:

### Nuki ###
lock:
  - platform: nuki
    host: !secret nuki_host
    token: !secret nuki_token

### Weather ###
weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

### Google calendar ###
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
  track_new_calendar: true

### Include Files ###
automation: !include automations.yaml
camera: !include cameras.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
ios: !include ios.yaml
media_player: !include mediaplayer.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shelly: !include shelly.yaml

### Include Directories ###
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by JeremiahGillis** [comment]
I have a similar issue using 0.105.4 in virtualenv on FreeNAS per https://community.home-assistant.io/t/home-assistant-core-freenas-community-plugin/170542.

Any GUI page in Home Assistant Core refreshes once every 30 seconds. I first noticed this when using the Configurator. However any page will refresh, even the Overview page. This issue persists with Google Chrome and Microsoft Edge.

**Comment by blattmann** [comment]
I was trying to go through all my logs and I had found issues with [Hacs](https://github.com/hacs/integration). I did reinstall Hacs and the refreshing issue was gone.
My issue is solved so far but as long as @JeremiahGillis still has problems I would not like to close this issue.

**Comment by JeremiahGillis** [comment]
@blattmann Going off your theory, I removed Hacs integration and deleted the folder. The 30 second periodic refreshing issues continued.

I just reinstalled Home Assistant Core without installing AppDeamon, Configurator, and Hacs. The periodic refreshing still occurs. I have no issues in the main screen log. I will dig through the full logs later. I also posted my issues to link in my previous post.

Maybe I will also try to reinstall Home Assistant Core without pointing to my configuration and data. I can go through the setup process and see if this issue is still present.

**Comment by JeremiahGillis** [comment]
@blattmann My issue appears to be with HAProxy. I don't have the periodic refresh if I access Home Assistant Core GUI via ip address. It only happens when using my reverse proxy. I fixed it by adjusting some http options in the configuration.yaml. You can go ahead and close this.

**Comment by blattmann** [comment]
@JeremiahGillis Thanks for your update.
Closing this issue.

**Comment by Wolvenmoon** [comment]
Hey, I'm having the same issue and am behind HAProxy. This is what comes up on Google. I'm completely new to HA configuration so it's not obvious to me what I need to change. What configuration changes did you make so that it would work correctly behind HAProxy?

**Comment by thisisbenwoo** [comment]
> @blattmann My issue appears to be with HAProxy. I don't have the periodic refresh if I access Home Assistant Core GUI via ip address. It only happens when using my reverse proxy. I fixed it by adjusting some http options in the configuration.yaml. You can go ahead and close this.

Can you advise what changes you made please? I'm experiencing this issue with 2021.06.all
