### ISSUE TITLE
Rendering Grayed out in Older iOS version ( 9.3.5 on iPad)

### ISSUE THREAD

**Issue by gb53smith** [home-assistant/home-assistant-polymer#780]
Is it possible to detect older iPads and iPhones and give them some extended use as Home Assistance monitors?
Reported this with hass.io **0.60.0**
Transferred here from
https://github.com/home-assistant/home-assistant/issues/9053

Using  
```
frontend: 
  javascript_version: es5
```
Just to see anything in the iOS app

**Comment by robmarkcole** [comment]
Still an issue in 0.60

**Comment by ciotlosm** [comment]
Try using in your config:
```
frontend: 
  javascript_version: es5
```

See if the issue is still present

**Comment by robmarkcole** [comment]
Issue still present I'm afraid

**Comment by ciotlosm** [comment]
I deleted my comment as I re-read your post where you specifically mentioned the use of javascript_version. 
The original issue https://github.com/home-assistant/home-assistant/issues/9053#issuecomment-323929821 mentions that this could be a problem with support of Polymer 2, as it seems some features require IOS >= 10.3

I guess this is harder to support fix, but posting here gathered details if someone is going to pickup the issue not to go through the same digging process :)

**Comment by themanieldaniel** [comment]
I am having the rendering issue on my iOS 9 devices. 

I read here (https://www.polymer-project.org/2.0/docs/es6) that polymer 2 should be rendered using es5 instead of es6 in order to be compatible with all devices. Is home assistant able to do that?

gb53smith said:
> Using
> 
> ```
> frontend: 
>   javascript_version: es5
> ```
> Just to see anything in the iOS app

I am confused if that is a suggestion to add to home assistant or if that is an already built in feature. It doesn't seem to do anything when I add it to my configuration.yaml file.

**Comment by ciotlosm** [comment]
@themanieldaniel it's built in. Try adding those settings to your configuration, restart your home assistant and try reinstalling your IOS app and check again.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant/pull/11387

**Comment by themanieldaniel** [comment]
I have not had good success yet in getting my iOS 9 device to display properly. The article reference by @balloob refers to iOS 10 devices. I think this may still be a separate issue.

I have tried the steps suggested by @ciotlosm, added the settings to configuration.yaml, restarted Home Assistant and reinstalled the iOS 9 app. Still getting the greyed out and transparent controls.

**Comment by gb53smith** [comment]
I don't know why @balloob closed this?
The title specifically mentions a 9.3.5 iPad

**Comment by matthieut59** [comment]
please reopen the issue, it s still occuring on ipad 9.3.5 :/

**Comment by NovapaX** [comment]
This is being worked on in https://github.com/home-assistant/home-assistant-polymer/pull/901

**Comment by marcgarciamarti** [comment]
Hi, is this being worked on? I can confirm this issue is still happening on 0.96.5. Any chance I can help with testing? I see there are separate issues. Can anybody point me to the most comprehensive one?
